'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class English
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Trader.English", GetType(English).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ___.
        '''</summary>
        Friend Shared ReadOnly Property __a19() As String
            Get
                Return ResourceManager.GetString("__a19", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Account.
        '''</summary>
        Friend Shared ReadOnly Property account() As String
            Get
                Return ResourceManager.GetString("account", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Account Number.
        '''</summary>
        Friend Shared ReadOnly Property account_number() As String
            Get
                Return ResourceManager.GetString("account_number", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Account / Subaccount.
        '''</summary>
        Friend Shared ReadOnly Property account_subaccount() As String
            Get
                Return ResourceManager.GetString("account_subaccount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Action.
        '''</summary>
        Friend Shared ReadOnly Property action() As String
            Get
                Return ResourceManager.GetString("action", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Active.
        '''</summary>
        Friend Shared ReadOnly Property active() As String
            Get
                Return ResourceManager.GetString("active", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add this document to the customer document  file?.
        '''</summary>
        Friend Shared ReadOnly Property add_this_document_to_the_customer_document_file() As String
            Get
                Return ResourceManager.GetString("add_this_document_to_the_customer_document_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address.
        '''</summary>
        Friend Shared ReadOnly Property address() As String
            Get
                Return ResourceManager.GetString("address", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address and Contact Details.
        '''</summary>
        Friend Shared ReadOnly Property address_and_contact_details() As String
            Get
                Return ResourceManager.GetString("address_and_contact_details", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address and Contact Information.
        '''</summary>
        Friend Shared ReadOnly Property address_and_contact_information() As String
            Get
                Return ResourceManager.GetString("address_and_contact_information", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address - Street.
        '''</summary>
        Friend Shared ReadOnly Property address_street() As String
            Get
                Return ResourceManager.GetString("address_street", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Advisor.
        '''</summary>
        Friend Shared ReadOnly Property advisor() As String
            Get
                Return ResourceManager.GetString("advisor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Advisors.
        '''</summary>
        Friend Shared ReadOnly Property advisors() As String
            Get
                Return ResourceManager.GetString("advisors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Advisory.
        '''</summary>
        Friend Shared ReadOnly Property advisory() As String
            Get
                Return ResourceManager.GetString("advisory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VAT number.
        '''</summary>
        Friend Shared ReadOnly Property afm() As String
            Get
                Return ResourceManager.GetString("afm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aggressive Growth.
        '''</summary>
        Friend Shared ReadOnly Property aggressive_growth() As String
            Get
                Return ResourceManager.GetString("aggressive_growth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Alerts.
        '''</summary>
        Friend Shared ReadOnly Property alerts() As String
            Get
                Return ResourceManager.GetString("alerts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All.
        '''</summary>
        Friend Shared ReadOnly Property all() As String
            Get
                Return ResourceManager.GetString("all", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All Orders.
        '''</summary>
        Friend Shared ReadOnly Property all_orders() As String
            Get
                Return ResourceManager.GetString("all_orders", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All Transactions.
        '''</summary>
        Friend Shared ReadOnly Property all_transactions() As String
            Get
                Return ResourceManager.GetString("all_transactions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AMKA.
        '''</summary>
        Friend Shared ReadOnly Property amka() As String
            Get
                Return ResourceManager.GetString("amka", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Amount.
        '''</summary>
        Friend Shared ReadOnly Property amount() As String
            Get
                Return ResourceManager.GetString("amount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AUM.
        '''</summary>
        Friend Shared ReadOnly Property aum() As String
            Get
                Return ResourceManager.GetString("aum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to B.
        '''</summary>
        Friend Shared ReadOnly Property b() As String
            Get
                Return ResourceManager.GetString("b", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to B&amp;S.
        '''</summary>
        Friend Shared ReadOnly Property b_s() As String
            Get
                Return ResourceManager.GetString("b_s", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Balanced Growth.
        '''</summary>
        Friend Shared ReadOnly Property balanced_growth() As String
            Get
                Return ResourceManager.GetString("balanced_growth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bank.
        '''</summary>
        Friend Shared ReadOnly Property bank() As String
            Get
                Return ResourceManager.GetString("bank", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Black List.
        '''</summary>
        Friend Shared ReadOnly Property black_list() As String
            Get
                Return ResourceManager.GetString("black_list", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bloomberg Code.
        '''</summary>
        Friend Shared ReadOnly Property bloomberg_code() As String
            Get
                Return ResourceManager.GetString("bloomberg_code", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bonds.
        '''</summary>
        Friend Shared ReadOnly Property bonds() As String
            Get
                Return ResourceManager.GetString("bonds", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Branch.
        '''</summary>
        Friend Shared ReadOnly Property branch() As String
            Get
                Return ResourceManager.GetString("branch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Brokerage and Intermediary.
        '''</summary>
        Friend Shared ReadOnly Property brokerage_and_intermediary() As String
            Get
                Return ResourceManager.GetString("brokerage_and_intermediary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Brokerage Comissions Reports.
        '''</summary>
        Friend Shared ReadOnly Property brokerage_comissions_reports() As String
            Get
                Return ResourceManager.GetString("brokerage_comissions_reports", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Brokerage Settlements.
        '''</summary>
        Friend Shared ReadOnly Property brokerage_settlements() As String
            Get
                Return ResourceManager.GetString("brokerage_settlements", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BS.
        '''</summary>
        Friend Shared ReadOnly Property bs() As String
            Get
                Return ResourceManager.GetString("bs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Buy.
        '''</summary>
        Friend Shared ReadOnly Property buy() As String
            Get
                Return ResourceManager.GetString("buy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend Shared ReadOnly Property cancel() As String
            Get
                Return ResourceManager.GetString("cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Δεν μπορεί να επιλεχθεί το ίδιο currency account στο ίδιο subaccount.
        '''</summary>
        Friend Shared ReadOnly Property cash_account_warning() As String
            Get
                Return ResourceManager.GetString("cash_account_warning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Class.
        '''</summary>
        Friend Shared ReadOnly Property category() As String
            Get
                Return ResourceManager.GetString("category", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Certificate Information.
        '''</summary>
        Friend Shared ReadOnly Property certificate_Information() As String
            Get
                Return ResourceManager.GetString("certificate_Information", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Checking.
        '''</summary>
        Friend Shared ReadOnly Property checking() As String
            Get
                Return ResourceManager.GetString("checking", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Citizenship.
        '''</summary>
        Friend Shared ReadOnly Property citizenship() As String
            Get
                Return ResourceManager.GetString("citizenship", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to City.
        '''</summary>
        Friend Shared ReadOnly Property city() As String
            Get
                Return ResourceManager.GetString("city", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clear Filters.
        '''</summary>
        Friend Shared ReadOnly Property clear_filters() As String
            Get
                Return ResourceManager.GetString("clear_filters", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Client.
        '''</summary>
        Friend Shared ReadOnly Property client() As String
            Get
                Return ResourceManager.GetString("client", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Client Information.
        '''</summary>
        Friend Shared ReadOnly Property client_information() As String
            Get
                Return ResourceManager.GetString("client_information", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Client List.
        '''</summary>
        Friend Shared ReadOnly Property client_list() As String
            Get
                Return ResourceManager.GetString("client_list", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Client Search.
        '''</summary>
        Friend Shared ReadOnly Property client_search() As String
            Get
                Return ResourceManager.GetString("client_search", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Client Updating.
        '''</summary>
        Friend Shared ReadOnly Property client_updating() As String
            Get
                Return ResourceManager.GetString("client_updating", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Client&apos;s Bank Accounts.
        '''</summary>
        Friend Shared ReadOnly Property clients_bank_accounts() As String
            Get
                Return ResourceManager.GetString("clients_bank_accounts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clients List.
        '''</summary>
        Friend Shared ReadOnly Property clients_list() As String
            Get
                Return ResourceManager.GetString("clients_list", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clients Search.
        '''</summary>
        Friend Shared ReadOnly Property clients_search() As String
            Get
                Return ResourceManager.GetString("clients_search", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Client’s update.
        '''</summary>
        Friend Shared ReadOnly Property clients_update() As String
            Get
                Return ResourceManager.GetString("clients_update", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Code.
        '''</summary>
        Friend Shared ReadOnly Property code() As String
            Get
                Return ResourceManager.GetString("code", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Coment.
        '''</summary>
        Friend Shared ReadOnly Property coment() As String
            Get
                Return ResourceManager.GetString("coment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Coments.
        '''</summary>
        Friend Shared ReadOnly Property coments() As String
            Get
                Return ResourceManager.GetString("coments", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Comment.
        '''</summary>
        Friend Shared ReadOnly Property comment() As String
            Get
                Return ResourceManager.GetString("comment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Commercial Management &amp; Accounting.
        '''</summary>
        Friend Shared ReadOnly Property commercial_management_accounting() As String
            Get
                Return ResourceManager.GetString("commercial_management_accounting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Commisions.
        '''</summary>
        Friend Shared ReadOnly Property commisions() As String
            Get
                Return ResourceManager.GetString("commisions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Commission.
        '''</summary>
        Friend Shared ReadOnly Property commission() As String
            Get
                Return ResourceManager.GetString("commission", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Commission Calculation.
        '''</summary>
        Friend Shared ReadOnly Property commission_calculation() As String
            Get
                Return ResourceManager.GetString("commission_calculation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Commissions.
        '''</summary>
        Friend Shared ReadOnly Property commissions() As String
            Get
                Return ResourceManager.GetString("commissions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Company.
        '''</summary>
        Friend Shared ReadOnly Property company() As String
            Get
                Return ResourceManager.GetString("company", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Company&apos;s commission.
        '''</summary>
        Friend Shared ReadOnly Property companys_commission() As String
            Get
                Return ResourceManager.GetString("companys_commission", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connection Method.
        '''</summary>
        Friend Shared ReadOnly Property connection_method() As String
            Get
                Return ResourceManager.GetString("connection_method", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact.
        '''</summary>
        Friend Shared ReadOnly Property contact() As String
            Get
                Return ResourceManager.GetString("contact", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact and prospective clients.
        '''</summary>
        Friend Shared ReadOnly Property contact_and_prospective_clients() As String
            Get
                Return ResourceManager.GetString("contact_and_prospective_clients", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact Details.
        '''</summary>
        Friend Shared ReadOnly Property contact_details() As String
            Get
                Return ResourceManager.GetString("contact_details", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact Information.
        '''</summary>
        Friend Shared ReadOnly Property contact_information() As String
            Get
                Return ResourceManager.GetString("contact_information", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contract.
        '''</summary>
        Friend Shared ReadOnly Property contract() As String
            Get
                Return ResourceManager.GetString("contract", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contract Details.
        '''</summary>
        Friend Shared ReadOnly Property contract_details() As String
            Get
                Return ResourceManager.GetString("contract_details", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contracts.
        '''</summary>
        Friend Shared ReadOnly Property contracts() As String
            Get
                Return ResourceManager.GetString("contracts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Countries.
        '''</summary>
        Friend Shared ReadOnly Property countries() As String
            Get
                Return ResourceManager.GetString("countries", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Country.
        '''</summary>
        Friend Shared ReadOnly Property country() As String
            Get
                Return ResourceManager.GetString("country", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Country of Taxation.
        '''</summary>
        Friend Shared ReadOnly Property country_of_taxation() As String
            Get
                Return ResourceManager.GetString("country_of_taxation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Currency.
        '''</summary>
        Friend Shared ReadOnly Property currency() As String
            Get
                Return ResourceManager.GetString("currency", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Customer.
        '''</summary>
        Friend Shared ReadOnly Property customer() As String
            Get
                Return ResourceManager.GetString("customer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Customer Information.
        '''</summary>
        Friend Shared ReadOnly Property customer_information() As String
            Get
                Return ResourceManager.GetString("customer_information", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Customer Name.
        '''</summary>
        Friend Shared ReadOnly Property customer_name() As String
            Get
                Return ResourceManager.GetString("customer_name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Customers List.
        '''</summary>
        Friend Shared ReadOnly Property customers_list() As String
            Get
                Return ResourceManager.GetString("customers_list", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data changes.
        '''</summary>
        Friend Shared ReadOnly Property data_changes() As String
            Get
                Return ResourceManager.GetString("data_changes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data Entry.
        '''</summary>
        Friend Shared ReadOnly Property data_entry() As String
            Get
                Return ResourceManager.GetString("data_entry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data initialisation.
        '''</summary>
        Friend Shared ReadOnly Property data_initialisation() As String
            Get
                Return ResourceManager.GetString("data_initialisation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date.
        '''</summary>
        Friend Shared ReadOnly Property date_() As String
            Get
                Return ResourceManager.GetString("date_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date from.
        '''</summary>
        Friend Shared ReadOnly Property date_from() As String
            Get
                Return ResourceManager.GetString("date_from", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date of Birth.
        '''</summary>
        Friend Shared ReadOnly Property date_of_birth() As String
            Get
                Return ResourceManager.GetString("date_of_birth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date of Issuing.
        '''</summary>
        Friend Shared ReadOnly Property date_of_issuing() As String
            Get
                Return ResourceManager.GetString("date_of_issuing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date of Registration.
        '''</summary>
        Friend Shared ReadOnly Property date_of_registration() As String
            Get
                Return ResourceManager.GetString("date_of_registration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date Start / End.
        '''</summary>
        Friend Shared ReadOnly Property date_start_end() As String
            Get
                Return ResourceManager.GetString("date_start_end", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Derivatives.
        '''</summary>
        Friend Shared ReadOnly Property derivatives() As String
            Get
                Return ResourceManager.GetString("derivatives", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Description.
        '''</summary>
        Friend Shared ReadOnly Property description() As String
            Get
                Return ResourceManager.GetString("description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Digital Settlement Advice.
        '''</summary>
        Friend Shared ReadOnly Property digital_settlement_advice() As String
            Get
                Return ResourceManager.GetString("digital_settlement_advice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Discount.
        '''</summary>
        Friend Shared ReadOnly Property discount() As String
            Get
                Return ResourceManager.GetString("discount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Discretionary Portfolio Management.
        '''</summary>
        Friend Shared ReadOnly Property discretionary_portfolio_management() As String
            Get
                Return ResourceManager.GetString("discretionary_portfolio_management", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DMS.
        '''</summary>
        Friend Shared ReadOnly Property dms() As String
            Get
                Return ResourceManager.GetString("dms", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Doc Type ID.
        '''</summary>
        Friend Shared ReadOnly Property doc_type_id() As String
            Get
                Return ResourceManager.GetString("doc_type_id", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Document Type.
        '''</summary>
        Friend Shared ReadOnly Property document_type() As String
            Get
                Return ResourceManager.GetString("document_type", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Documentation.
        '''</summary>
        Friend Shared ReadOnly Property documentation() As String
            Get
                Return ResourceManager.GetString("documentation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Documents.
        '''</summary>
        Friend Shared ReadOnly Property documents() As String
            Get
                Return ResourceManager.GetString("documents", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Documents for applicants.
        '''</summary>
        Friend Shared ReadOnly Property documents_for_applicants() As String
            Get
                Return ResourceManager.GetString("documents_for_applicants", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DOY.
        '''</summary>
        Friend Shared ReadOnly Property doy() As String
            Get
                Return ResourceManager.GetString("doy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Duration.
        '''</summary>
        Friend Shared ReadOnly Property duration() As String
            Get
                Return ResourceManager.GetString("duration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to E-mail.
        '''</summary>
        Friend Shared ReadOnly Property e_mail() As String
            Get
                Return ResourceManager.GetString("e_mail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter Portfolio.
        '''</summary>
        Friend Shared ReadOnly Property enter_profitCenter_subacc() As String
            Get
                Return ResourceManager.GetString("enter_profitCenter_subacc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Entry Basis.
        '''</summary>
        Friend Shared ReadOnly Property entry_basis() As String
            Get
                Return ResourceManager.GetString("entry_basis", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Equities.
        '''</summary>
        Friend Shared ReadOnly Property equities() As String
            Get
                Return ResourceManager.GetString("equities", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ETF.
        '''</summary>
        Friend Shared ReadOnly Property etf() As String
            Get
                Return ResourceManager.GetString("etf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Executed command.
        '''</summary>
        Friend Shared ReadOnly Property executed_command() As String
            Get
                Return ResourceManager.GetString("executed_command", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Execution.
        '''</summary>
        Friend Shared ReadOnly Property Execution() As String
            Get
                Return ResourceManager.GetString("Execution", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Execution date.
        '''</summary>
        Friend Shared ReadOnly Property execution_date() As String
            Get
                Return ResourceManager.GetString("execution_date", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Execution date from.
        '''</summary>
        Friend Shared ReadOnly Property execution_date_from() As String
            Get
                Return ResourceManager.GetString("execution_date_from", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Execution Venue.
        '''</summary>
        Friend Shared ReadOnly Property execution_venue() As String
            Get
                Return ResourceManager.GetString("execution_venue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exit.
        '''</summary>
        Friend Shared ReadOnly Property exit_() As String
            Get
                Return ResourceManager.GetString("exit_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Expire Date.
        '''</summary>
        Friend Shared ReadOnly Property expire_date() As String
            Get
                Return ResourceManager.GetString("expire_date", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Facility Options.
        '''</summary>
        Friend Shared ReadOnly Property facility_options() As String
            Get
                Return ResourceManager.GetString("facility_options", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Father&apos;s Surname.
        '''</summary>
        Friend Shared ReadOnly Property fathers_surname() As String
            Get
                Return ResourceManager.GetString("fathers_surname", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fax.
        '''</summary>
        Friend Shared ReadOnly Property fax() As String
            Get
                Return ResourceManager.GetString("fax", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Female.
        '''</summary>
        Friend Shared ReadOnly Property female() As String
            Get
                Return ResourceManager.GetString("female", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File.
        '''</summary>
        Friend Shared ReadOnly Property file() As String
            Get
                Return ResourceManager.GetString("file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File Name.
        '''</summary>
        Friend Shared ReadOnly Property file_name() As String
            Get
                Return ResourceManager.GetString("file_name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Filter.
        '''</summary>
        Friend Shared ReadOnly Property filter() As String
            Get
                Return ResourceManager.GetString("filter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Final.
        '''</summary>
        Friend Shared ReadOnly Property final() As String
            Get
                Return ResourceManager.GetString("final", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Final Commission.
        '''</summary>
        Friend Shared ReadOnly Property final_commission() As String
            Get
                Return ResourceManager.GetString("final_commission", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fixed Advance.
        '''</summary>
        Friend Shared ReadOnly Property fixed_advance() As String
            Get
                Return ResourceManager.GetString("fixed_advance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fixed Income.
        '''</summary>
        Friend Shared ReadOnly Property fixed_income() As String
            Get
                Return ResourceManager.GetString("fixed_income", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Full name.
        '''</summary>
        Friend Shared ReadOnly Property full_name() As String
            Get
                Return ResourceManager.GetString("full_name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to General Information.
        '''</summary>
        Friend Shared ReadOnly Property general_information() As String
            Get
                Return ResourceManager.GetString("general_information", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GTC.
        '''</summary>
        Friend Shared ReadOnly Property gtc() As String
            Get
                Return ResourceManager.GetString("gtc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Help.
        '''</summary>
        Friend Shared ReadOnly Property help() As String
            Get
                Return ResourceManager.GetString("help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HF Greek Products of Fixed Income.
        '''</summary>
        Friend Shared ReadOnly Property hf_greek_products_of_fixed_income() As String
            Get
                Return ResourceManager.GetString("hf_greek_products_of_fixed_income", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HF International Equities.
        '''</summary>
        Friend Shared ReadOnly Property hf_international_equities() As String
            Get
                Return ResourceManager.GetString("hf_international_equities", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HF International Fixed Income.
        '''</summary>
        Friend Shared ReadOnly Property hf_international_fixed_income() As String
            Get
                Return ResourceManager.GetString("hf_international_fixed_income", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to History.
        '''</summary>
        Friend Shared ReadOnly Property history() As String
            Get
                Return ResourceManager.GetString("history", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ID.
        '''</summary>
        Friend Shared ReadOnly Property id() As String
            Get
                Return ResourceManager.GetString("id", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inactive.
        '''</summary>
        Friend Shared ReadOnly Property inactive() As String
            Get
                Return ResourceManager.GetString("inactive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Income 80/20.
        '''</summary>
        Friend Shared ReadOnly Property income_80_20() As String
            Get
                Return ResourceManager.GetString("income_80_20", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Indexes.
        '''</summary>
        Friend Shared ReadOnly Property indexes() As String
            Get
                Return ResourceManager.GetString("indexes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Informing.
        '''</summary>
        Friend Shared ReadOnly Property informing() As String
            Get
                Return ResourceManager.GetString("informing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Informing ways.
        '''</summary>
        Friend Shared ReadOnly Property informing_ways() As String
            Get
                Return ResourceManager.GetString("informing_ways", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Institutional.
        '''</summary>
        Friend Shared ReadOnly Property institutional() As String
            Get
                Return ResourceManager.GetString("institutional", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Investment Advices.
        '''</summary>
        Friend Shared ReadOnly Property investment_advices() As String
            Get
                Return ResourceManager.GetString("investment_advices", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Investment Advise.
        '''</summary>
        Friend Shared ReadOnly Property investment_advise() As String
            Get
                Return ResourceManager.GetString("investment_advise", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Investment Committees.
        '''</summary>
        Friend Shared ReadOnly Property investment_committees() As String
            Get
                Return ResourceManager.GetString("investment_committees", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Investment Advices.
        '''</summary>
        Friend Shared ReadOnly Property investment_dvices() As String
            Get
                Return ResourceManager.GetString("investment_dvices", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Investment Policy.
        '''</summary>
        Friend Shared ReadOnly Property investment_policy() As String
            Get
                Return ResourceManager.GetString("investment_policy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Investment Proposals.
        '''</summary>
        Friend Shared ReadOnly Property investment_proposals() As String
            Get
                Return ResourceManager.GetString("investment_proposals", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ISIN.
        '''</summary>
        Friend Shared ReadOnly Property isin() As String
            Get
                Return ResourceManager.GetString("isin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Issue.
        '''</summary>
        Friend Shared ReadOnly Property issue() As String
            Get
                Return ResourceManager.GetString("issue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Issuing Authority.
        '''</summary>
        Friend Shared ReadOnly Property issuing_authority() As String
            Get
                Return ResourceManager.GetString("issuing_authority", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Joint.
        '''</summary>
        Friend Shared ReadOnly Property joint() As String
            Get
                Return ResourceManager.GetString("joint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Joint Owners.
        '''</summary>
        Friend Shared ReadOnly Property joint_owners() As String
            Get
                Return ResourceManager.GetString("joint_owners", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Labels.
        '''</summary>
        Friend Shared ReadOnly Property labels() As String
            Get
                Return ResourceManager.GetString("labels", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Language.
        '''</summary>
        Friend Shared ReadOnly Property language() As String
            Get
                Return ResourceManager.GetString("language", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Legal Documentation.
        '''</summary>
        Friend Shared ReadOnly Property legal_documentation() As String
            Get
                Return ResourceManager.GetString("legal_documentation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Legal Documents.
        '''</summary>
        Friend Shared ReadOnly Property legal_documents() As String
            Get
                Return ResourceManager.GetString("legal_documents", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to List Print.
        '''</summary>
        Friend Shared ReadOnly Property list_print() As String
            Get
                Return ResourceManager.GetString("list_print", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Male.
        '''</summary>
        Friend Shared ReadOnly Property male() As String
            Get
                Return ResourceManager.GetString("male", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Management.
        '''</summary>
        Friend Shared ReadOnly Property management() As String
            Get
                Return ResourceManager.GetString("management", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Managment Fees.
        '''</summary>
        Friend Shared ReadOnly Property managment_fees() As String
            Get
                Return ResourceManager.GetString("managment_fees", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Managment Fees Reports.
        '''</summary>
        Friend Shared ReadOnly Property managment_fees_reports() As String
            Get
                Return ResourceManager.GetString("managment_fees_reports", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Maximize.
        '''</summary>
        Friend Shared ReadOnly Property maximize() As String
            Get
                Return ResourceManager.GetString("maximize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Miscellaneous.
        '''</summary>
        Friend Shared ReadOnly Property miscellaneous() As String
            Get
                Return ResourceManager.GetString("miscellaneous", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Miscellaneous Lists.
        '''</summary>
        Friend Shared ReadOnly Property miscellaneous_lists() As String
            Get
                Return ResourceManager.GetString("miscellaneous_lists", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mobile.
        '''</summary>
        Friend Shared ReadOnly Property mobile() As String
            Get
                Return ResourceManager.GetString("mobile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Money Market.
        '''</summary>
        Friend Shared ReadOnly Property money_market() As String
            Get
                Return ResourceManager.GetString("money_market", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mother&apos;s Surname.
        '''</summary>
        Friend Shared ReadOnly Property mothers_surname() As String
            Get
                Return ResourceManager.GetString("mothers_surname", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mutual Fund.
        '''</summary>
        Friend Shared ReadOnly Property mutual_fund() As String
            Get
                Return ResourceManager.GetString("mutual_fund", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mutual Funds.
        '''</summary>
        Friend Shared ReadOnly Property mutual_funds() As String
            Get
                Return ResourceManager.GetString("mutual_funds", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to N.
        '''</summary>
        Friend Shared ReadOnly Property n() As String
            Get
                Return ResourceManager.GetString("n", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name.
        '''</summary>
        Friend Shared ReadOnly Property name() As String
            Get
                Return ResourceManager.GetString("name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nee.
        '''</summary>
        Friend Shared ReadOnly Property nee() As String
            Get
                Return ResourceManager.GetString("nee", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Needs.
        '''</summary>
        Friend Shared ReadOnly Property needs() As String
            Get
                Return ResourceManager.GetString("needs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Product.
        '''</summary>
        Friend Shared ReadOnly Property new_product() As String
            Get
                Return ResourceManager.GetString("new_product", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No.
        '''</summary>
        Friend Shared ReadOnly Property no() As String
            Get
                Return ResourceManager.GetString("no", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not Checked.
        '''</summary>
        Friend Shared ReadOnly Property not_checked() As String
            Get
                Return ResourceManager.GetString("not_checked", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Note.
        '''</summary>
        Friend Shared ReadOnly Property note() As String
            Get
                Return ResourceManager.GetString("note", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Notes.
        '''</summary>
        Friend Shared ReadOnly Property notes() As String
            Get
                Return ResourceManager.GetString("notes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number.
        '''</summary>
        Friend Shared ReadOnly Property number() As String
            Get
                Return ResourceManager.GetString("number", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number Account.
        '''</summary>
        Friend Shared ReadOnly Property number_account() As String
            Get
                Return ResourceManager.GetString("number_account", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Only active clients.
        '''</summary>
        Friend Shared ReadOnly Property only_active_clients() As String
            Get
                Return ResourceManager.GetString("only_active_clients", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Only Executed Transactions.
        '''</summary>
        Friend Shared ReadOnly Property only_executed_transactions() As String
            Get
                Return ResourceManager.GetString("only_executed_transactions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Only transmitted Transactions.
        '''</summary>
        Friend Shared ReadOnly Property only_transmitted_transactions() As String
            Get
                Return ResourceManager.GetString("only_transmitted_transactions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Only unexecuted Transactions.
        '''</summary>
        Friend Shared ReadOnly Property only_unexecuted_transactions() As String
            Get
                Return ResourceManager.GetString("only_unexecuted_transactions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Only untransmitted Transactions.
        '''</summary>
        Friend Shared ReadOnly Property only_untransmitted_transactions() As String
            Get
                Return ResourceManager.GetString("only_untransmitted_transactions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Options.
        '''</summary>
        Friend Shared ReadOnly Property options() As String
            Get
                Return ResourceManager.GetString("options", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Order.
        '''</summary>
        Friend Shared ReadOnly Property order() As String
            Get
                Return ResourceManager.GetString("order", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Order Book.
        '''</summary>
        Friend Shared ReadOnly Property order_book() As String
            Get
                Return ResourceManager.GetString("order_book", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Order Cancelation.
        '''</summary>
        Friend Shared ReadOnly Property order_cancelation() As String
            Get
                Return ResourceManager.GetString("order_cancelation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Order Execution.
        '''</summary>
        Friend Shared ReadOnly Property order_execution() As String
            Get
                Return ResourceManager.GetString("order_execution", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Order Receipt Way.
        '''</summary>
        Friend Shared ReadOnly Property order_receipt_way() As String
            Get
                Return ResourceManager.GetString("order_receipt_way", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Orders Search.
        '''</summary>
        Friend Shared ReadOnly Property orders_search() As String
            Get
                Return ResourceManager.GetString("orders_search", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Orders Transfer.
        '''</summary>
        Friend Shared ReadOnly Property orders_transfer() As String
            Get
                Return ResourceManager.GetString("orders_transfer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to P.
        '''</summary>
        Friend Shared ReadOnly Property p() As String
            Get
                Return ResourceManager.GetString("p", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Package.
        '''</summary>
        Friend Shared ReadOnly Property package() As String
            Get
                Return ResourceManager.GetString("package", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Package commission.
        '''</summary>
        Friend Shared ReadOnly Property package_commission() As String
            Get
                Return ResourceManager.GetString("package_commission", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Package discount.
        '''</summary>
        Friend Shared ReadOnly Property package_discount() As String
            Get
                Return ResourceManager.GetString("package_discount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Package ID.
        '''</summary>
        Friend Shared ReadOnly Property package_id() As String
            Get
                Return ResourceManager.GetString("package_id", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Parameter.
        '''</summary>
        Friend Shared ReadOnly Property parameter() As String
            Get
                Return ResourceManager.GetString("parameter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PDF.
        '''</summary>
        Friend Shared ReadOnly Property pdf() As String
            Get
                Return ResourceManager.GetString("pdf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pensive.
        '''</summary>
        Friend Shared ReadOnly Property pensive() As String
            Get
                Return ResourceManager.GetString("pensive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Personal Settings.
        '''</summary>
        Friend Shared ReadOnly Property personal_settings() As String
            Get
                Return ResourceManager.GetString("personal_settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Personally.
        '''</summary>
        Friend Shared ReadOnly Property personally() As String
            Get
                Return ResourceManager.GetString("personally", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Phone.
        '''</summary>
        Friend Shared ReadOnly Property phone() As String
            Get
                Return ResourceManager.GetString("phone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Born place.
        '''</summary>
        Friend Shared ReadOnly Property place_of_birth() As String
            Get
                Return ResourceManager.GetString("place_of_birth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Police ID Card / Passport / other numb.
        '''</summary>
        Friend Shared ReadOnly Property police_id_card_passport_other_number() As String
            Get
                Return ResourceManager.GetString("police_id_card_passport_other_number", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Politically exposed persons.
        '''</summary>
        Friend Shared ReadOnly Property politically_exposed_persons() As String
            Get
                Return ResourceManager.GetString("politically_exposed_persons", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Post Mail.
        '''</summary>
        Friend Shared ReadOnly Property post_mail() As String
            Get
                Return ResourceManager.GetString("post_mail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Postcode.
        '''</summary>
        Friend Shared ReadOnly Property postcode() As String
            Get
                Return ResourceManager.GetString("postcode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Previous Value.
        '''</summary>
        Friend Shared ReadOnly Property previous_value() As String
            Get
                Return ResourceManager.GetString("previous_value", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Price.
        '''</summary>
        Friend Shared ReadOnly Property price() As String
            Get
                Return ResourceManager.GetString("price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Private.
        '''</summary>
        Friend Shared ReadOnly Property private_() As String
            Get
                Return ResourceManager.GetString("private_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Product.
        '''</summary>
        Friend Shared ReadOnly Property product() As String
            Get
                Return ResourceManager.GetString("product", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Product Categories.
        '''</summary>
        Friend Shared ReadOnly Property product_categories() As String
            Get
                Return ResourceManager.GetString("product_categories", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Product List.
        '''</summary>
        Friend Shared ReadOnly Property product_list() As String
            Get
                Return ResourceManager.GetString("product_list", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Product Prices.
        '''</summary>
        Friend Shared ReadOnly Property product_prices() As String
            Get
                Return ResourceManager.GetString("product_prices", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Profession.
        '''</summary>
        Friend Shared ReadOnly Property profession() As String
            Get
                Return ResourceManager.GetString("profession", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Profile.
        '''</summary>
        Friend Shared ReadOnly Property profile() As String
            Get
                Return ResourceManager.GetString("profile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prospective.
        '''</summary>
        Friend Shared ReadOnly Property prospective() As String
            Get
                Return ResourceManager.GetString("prospective", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prospective Clients.
        '''</summary>
        Friend Shared ReadOnly Property prospective_clients() As String
            Get
                Return ResourceManager.GetString("prospective_clients", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Provider.
        '''</summary>
        Friend Shared ReadOnly Property provider() As String
            Get
                Return ResourceManager.GetString("provider", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Publisher.
        '''</summary>
        Friend Shared ReadOnly Property publisher() As String
            Get
                Return ResourceManager.GetString("publisher", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Quantity.
        '''</summary>
        Friend Shared ReadOnly Property quantity() As String
            Get
                Return ResourceManager.GetString("quantity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Questionairre.
        '''</summary>
        Friend Shared ReadOnly Property questionnaire() As String
            Get
                Return ResourceManager.GetString("questionnaire", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rate.
        '''</summary>
        Friend Shared ReadOnly Property rate() As String
            Get
                Return ResourceManager.GetString("rate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rates.
        '''</summary>
        Friend Shared ReadOnly Property rates() As String
            Get
                Return ResourceManager.GetString("rates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Receipt.
        '''</summary>
        Friend Shared ReadOnly Property receipt() As String
            Get
                Return ResourceManager.GetString("receipt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Receipt time.
        '''</summary>
        Friend Shared ReadOnly Property receipt_time() As String
            Get
                Return ResourceManager.GetString("receipt_time", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Receipt way.
        '''</summary>
        Friend Shared ReadOnly Property receipt_way() As String
            Get
                Return ResourceManager.GetString("receipt_way", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Receipt way type.
        '''</summary>
        Friend Shared ReadOnly Property receipt_way_type() As String
            Get
                Return ResourceManager.GetString("receipt_way_type", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Receive and Transmit.
        '''</summary>
        Friend Shared ReadOnly Property receive_and_transmit() As String
            Get
                Return ResourceManager.GetString("receive_and_transmit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Receiving Transmission.
        '''</summary>
        Friend Shared ReadOnly Property receiving_transmission() As String
            Get
                Return ResourceManager.GetString("receiving_transmission", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Recipient Name.
        '''</summary>
        Friend Shared ReadOnly Property recipient_name() As String
            Get
                Return ResourceManager.GetString("recipient_name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reference Currency.
        '''</summary>
        Friend Shared ReadOnly Property reference_currency() As String
            Get
                Return ResourceManager.GetString("reference_currency", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Release Date.
        '''</summary>
        Friend Shared ReadOnly Property release_date() As String
            Get
                Return ResourceManager.GetString("release_date", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remaining Characters.
        '''</summary>
        Friend Shared ReadOnly Property remaining_characters() As String
            Get
                Return ResourceManager.GetString("remaining_characters", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Retrocession Fees.
        '''</summary>
        Friend Shared ReadOnly Property retrocession_fees() As String
            Get
                Return ResourceManager.GetString("retrocession_fees", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reuters Code.
        '''</summary>
        Friend Shared ReadOnly Property reuters_code() As String
            Get
                Return ResourceManager.GetString("reuters_code", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RM.
        '''</summary>
        Friend Shared ReadOnly Property rm() As String
            Get
                Return ResourceManager.GetString("rm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save.
        '''</summary>
        Friend Shared ReadOnly Property save() As String
            Get
                Return ResourceManager.GetString("save", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saving completed successfully.
        '''</summary>
        Friend Shared ReadOnly Property saving_completed_successfully() As String
            Get
                Return ResourceManager.GetString("saving_completed_successfully", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search.
        '''</summary>
        Friend Shared ReadOnly Property search() As String
            Get
                Return ResourceManager.GetString("search", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search Investment Proposals.
        '''</summary>
        Friend Shared ReadOnly Property search_investment_proposals() As String
            Get
                Return ResourceManager.GetString("search_investment_proposals", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sectors.
        '''</summary>
        Friend Shared ReadOnly Property sectors() As String
            Get
                Return ResourceManager.GetString("sectors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sell.
        '''</summary>
        Friend Shared ReadOnly Property sell() As String
            Get
                Return ResourceManager.GetString("sell", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Send.
        '''</summary>
        Friend Shared ReadOnly Property send() As String
            Get
                Return ResourceManager.GetString("send", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Send SMS.
        '''</summary>
        Friend Shared ReadOnly Property send_sms() As String
            Get
                Return ResourceManager.GetString("send_sms", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Service.
        '''</summary>
        Friend Shared ReadOnly Property service() As String
            Get
                Return ResourceManager.GetString("service", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Service package.
        '''</summary>
        Friend Shared ReadOnly Property service_package() As String
            Get
                Return ResourceManager.GetString("service_package", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Service Providers.
        '''</summary>
        Friend Shared ReadOnly Property service_providers() As String
            Get
                Return ResourceManager.GetString("service_providers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Services.
        '''</summary>
        Friend Shared ReadOnly Property services() As String
            Get
                Return ResourceManager.GetString("services", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Settlement Advice Checking.
        '''</summary>
        Friend Shared ReadOnly Property settlement_advice_checking() As String
            Get
                Return ResourceManager.GetString("settlement_advice_checking", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sex.
        '''</summary>
        Friend Shared ReadOnly Property sex() As String
            Get
                Return ResourceManager.GetString("sex", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shared Documents.
        '''</summary>
        Friend Shared ReadOnly Property shared_documents() As String
            Get
                Return ResourceManager.GetString("shared_documents", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show canceled orders.
        '''</summary>
        Friend Shared ReadOnly Property show_canceled_orders() As String
            Get
                Return ResourceManager.GetString("show_canceled_orders", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SN.
        '''</summary>
        Friend Shared ReadOnly Property sn() As String
            Get
                Return ResourceManager.GetString("sn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sound.
        '''</summary>
        Friend Shared ReadOnly Property sound() As String
            Get
                Return ResourceManager.GetString("sound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Spouse&apos;s Surname.
        '''</summary>
        Friend Shared ReadOnly Property spouses_surname() As String
            Get
                Return ResourceManager.GetString("spouses_surname", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stages of Contracts.
        '''</summary>
        Friend Shared ReadOnly Property stages_of_ontracts() As String
            Get
                Return ResourceManager.GetString("stages_of_ontracts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Starting Date.
        '''</summary>
        Friend Shared ReadOnly Property starting_date() As String
            Get
                Return ResourceManager.GetString("starting_date", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status.
        '''</summary>
        Friend Shared ReadOnly Property status() As String
            Get
                Return ResourceManager.GetString("status", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stock exchange.
        '''</summary>
        Friend Shared ReadOnly Property stock_exchange() As String
            Get
                Return ResourceManager.GetString("stock_exchange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Portfolio.
        '''</summary>
        Friend Shared ReadOnly Property subaccount() As String
            Get
                Return ResourceManager.GetString("subaccount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Subject.
        '''</summary>
        Friend Shared ReadOnly Property subject() As String
            Get
                Return ResourceManager.GetString("subject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Surname.
        '''</summary>
        Friend Shared ReadOnly Property surname() As String
            Get
                Return ResourceManager.GetString("surname", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tax Office.
        '''</summary>
        Friend Shared ReadOnly Property tax_office() As String
            Get
                Return ResourceManager.GetString("tax_office", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telephone.
        '''</summary>
        Friend Shared ReadOnly Property telephone() As String
            Get
                Return ResourceManager.GetString("telephone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Temporary Import Data.
        '''</summary>
        Friend Shared ReadOnly Property temporary_import_data() As String
            Get
                Return ResourceManager.GetString("temporary_import_data", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Text.
        '''</summary>
        Friend Shared ReadOnly Property text() As String
            Get
                Return ResourceManager.GetString("text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The introduction of the  surname is mandatory.
        '''</summary>
        Friend Shared ReadOnly Property the_introduction_of_the_surname_is_mandatory() As String
            Get
                Return ResourceManager.GetString("the_introduction_of_the_surname_is_mandatory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TIN.
        '''</summary>
        Friend Shared ReadOnly Property tin() As String
            Get
                Return ResourceManager.GetString("tin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Title.
        '''</summary>
        Friend Shared ReadOnly Property title() As String
            Get
                Return ResourceManager.GetString("title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tools.
        '''</summary>
        Friend Shared ReadOnly Property tools() As String
            Get
                Return ResourceManager.GetString("tools", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tools Options.
        '''</summary>
        Friend Shared ReadOnly Property tools_options() As String
            Get
                Return ResourceManager.GetString("tools_options", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tools Send SMS.
        '''</summary>
        Friend Shared ReadOnly Property tools_send_sms() As String
            Get
                Return ResourceManager.GetString("tools_send_sms", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tools Send SMS.
        '''</summary>
        Friend Shared ReadOnly Property tools_snd_sms() As String
            Get
                Return ResourceManager.GetString("tools_snd_sms", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Transaction.
        '''</summary>
        Friend Shared ReadOnly Property transaction() As String
            Get
                Return ResourceManager.GetString("transaction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Transaction commission.
        '''</summary>
        Friend Shared ReadOnly Property transaction_commission() As String
            Get
                Return ResourceManager.GetString("transaction_commission", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Transactions.
        '''</summary>
        Friend Shared ReadOnly Property transactions() As String
            Get
                Return ResourceManager.GetString("transactions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Transactions List.
        '''</summary>
        Friend Shared ReadOnly Property transactions_list() As String
            Get
                Return ResourceManager.GetString("transactions_list", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Transactions Search.
        '''</summary>
        Friend Shared ReadOnly Property transactions_search() As String
            Get
                Return ResourceManager.GetString("transactions_search", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Transmission.
        '''</summary>
        Friend Shared ReadOnly Property transmission() As String
            Get
                Return ResourceManager.GetString("transmission", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Transmission time.
        '''</summary>
        Friend Shared ReadOnly Property transmission_time() As String
            Get
                Return ResourceManager.GetString("transmission_time", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Transmitter.
        '''</summary>
        Friend Shared ReadOnly Property transmitter() As String
            Get
                Return ResourceManager.GetString("transmitter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Turnover.
        '''</summary>
        Friend Shared ReadOnly Property turnover() As String
            Get
                Return ResourceManager.GetString("turnover", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Turnover &amp; Fees.
        '''</summary>
        Friend Shared ReadOnly Property turnover_fees() As String
            Get
                Return ResourceManager.GetString("turnover_fees", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Type.
        '''</summary>
        Friend Shared ReadOnly Property type() As String
            Get
                Return ResourceManager.GetString("type", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Type of issue.
        '''</summary>
        Friend Shared ReadOnly Property type_of_issue() As String
            Get
                Return ResourceManager.GetString("type_of_issue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Until.
        '''</summary>
        Friend Shared ReadOnly Property until_() As String
            Get
                Return ResourceManager.GetString("until_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Updates file.
        '''</summary>
        Friend Shared ReadOnly Property updates_file() As String
            Get
                Return ResourceManager.GetString("updates_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Users.
        '''</summary>
        Friend Shared ReadOnly Property users() As String
            Get
                Return ResourceManager.GetString("users", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Via EAM-NET.
        '''</summary>
        Friend Shared ReadOnly Property via_eam_net() As String
            Get
                Return ResourceManager.GetString("via_eam_net", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Anamoni.
        '''</summary>
        Friend Shared ReadOnly Property waiting() As String
            Get
                Return ResourceManager.GetString("waiting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wrong amount.
        '''</summary>
        Friend Shared ReadOnly Property wrong_amount() As String
            Get
                Return ResourceManager.GetString("wrong_amount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Yes.
        '''</summary>
        Friend Shared ReadOnly Property yes() As String
            Get
                Return ResourceManager.GetString("yes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ZIP.
        '''</summary>
        Friend Shared ReadOnly Property zip() As String
            Get
                Return ResourceManager.GetString("zip", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
