//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Resources.English", typeof(English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ___.
        /// </summary>
        internal static string @__a19 {
            get {
                return ResourceManager.GetString("__a19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string account {
            get {
                return ResourceManager.GetString("account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        internal static string account_number {
            get {
                return ResourceManager.GetString("account_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account / Subaccount.
        /// </summary>
        internal static string account_subaccount {
            get {
                return ResourceManager.GetString("account_subaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string action {
            get {
                return ResourceManager.GetString("action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string active {
            get {
                return ResourceManager.GetString("active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add this document to the customer document  file?.
        /// </summary>
        internal static string add_this_document_to_the_customer_document_file {
            get {
                return ResourceManager.GetString("add_this_document_to_the_customer_document_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address and Contact Details.
        /// </summary>
        internal static string address_and_contact_details {
            get {
                return ResourceManager.GetString("address_and_contact_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address and Contact Information.
        /// </summary>
        internal static string address_and_contact_information {
            get {
                return ResourceManager.GetString("address_and_contact_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address - Street.
        /// </summary>
        internal static string address_street {
            get {
                return ResourceManager.GetString("address_street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advisor.
        /// </summary>
        internal static string advisor {
            get {
                return ResourceManager.GetString("advisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advisors.
        /// </summary>
        internal static string advisors {
            get {
                return ResourceManager.GetString("advisors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advisory.
        /// </summary>
        internal static string advisory {
            get {
                return ResourceManager.GetString("advisory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT number.
        /// </summary>
        internal static string afm {
            get {
                return ResourceManager.GetString("afm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggressive Growth.
        /// </summary>
        internal static string aggressive_growth {
            get {
                return ResourceManager.GetString("aggressive_growth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        internal static string alerts {
            get {
                return ResourceManager.GetString("alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Orders.
        /// </summary>
        internal static string all_orders {
            get {
                return ResourceManager.GetString("all_orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Transactions.
        /// </summary>
        internal static string all_transactions {
            get {
                return ResourceManager.GetString("all_transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMKA.
        /// </summary>
        internal static string amka {
            get {
                return ResourceManager.GetString("amka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUM.
        /// </summary>
        internal static string aum {
            get {
                return ResourceManager.GetString("aum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string b {
            get {
                return ResourceManager.GetString("b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B&amp;S.
        /// </summary>
        internal static string b_s {
            get {
                return ResourceManager.GetString("b_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balanced Growth.
        /// </summary>
        internal static string balanced_growth {
            get {
                return ResourceManager.GetString("balanced_growth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        internal static string bank {
            get {
                return ResourceManager.GetString("bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black List.
        /// </summary>
        internal static string black_list {
            get {
                return ResourceManager.GetString("black_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloomberg Code.
        /// </summary>
        internal static string bloomberg_code {
            get {
                return ResourceManager.GetString("bloomberg_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonds.
        /// </summary>
        internal static string bonds {
            get {
                return ResourceManager.GetString("bonds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        internal static string branch {
            get {
                return ResourceManager.GetString("branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brokerage and Intermediary.
        /// </summary>
        internal static string brokerage_and_intermediary {
            get {
                return ResourceManager.GetString("brokerage_and_intermediary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brokerage Comissions Reports.
        /// </summary>
        internal static string brokerage_comissions_reports {
            get {
                return ResourceManager.GetString("brokerage_comissions_reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brokerage Settlements.
        /// </summary>
        internal static string brokerage_settlements {
            get {
                return ResourceManager.GetString("brokerage_settlements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BS.
        /// </summary>
        internal static string bs {
            get {
                return ResourceManager.GetString("bs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        internal static string buy {
            get {
                return ResourceManager.GetString("buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν μπορεί να επιλεχθεί το ίδιο currency account στο ίδιο subaccount.
        /// </summary>
        internal static string cash_account_warning {
            get {
                return ResourceManager.GetString("cash_account_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Information.
        /// </summary>
        internal static string certificate_Information {
            get {
                return ResourceManager.GetString("certificate_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking.
        /// </summary>
        internal static string checking {
            get {
                return ResourceManager.GetString("checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citizenship.
        /// </summary>
        internal static string citizenship {
            get {
                return ResourceManager.GetString("citizenship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Filters.
        /// </summary>
        internal static string clear_filters {
            get {
                return ResourceManager.GetString("clear_filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        internal static string client {
            get {
                return ResourceManager.GetString("client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Information.
        /// </summary>
        internal static string client_information {
            get {
                return ResourceManager.GetString("client_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client List.
        /// </summary>
        internal static string client_list {
            get {
                return ResourceManager.GetString("client_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Search.
        /// </summary>
        internal static string client_search {
            get {
                return ResourceManager.GetString("client_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Updating.
        /// </summary>
        internal static string client_updating {
            get {
                return ResourceManager.GetString("client_updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client&apos;s Bank Accounts.
        /// </summary>
        internal static string clients_bank_accounts {
            get {
                return ResourceManager.GetString("clients_bank_accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients List.
        /// </summary>
        internal static string clients_list {
            get {
                return ResourceManager.GetString("clients_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients Search.
        /// </summary>
        internal static string clients_search {
            get {
                return ResourceManager.GetString("clients_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client’s update.
        /// </summary>
        internal static string clients_update {
            get {
                return ResourceManager.GetString("clients_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coment.
        /// </summary>
        internal static string coment {
            get {
                return ResourceManager.GetString("coment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coments.
        /// </summary>
        internal static string coments {
            get {
                return ResourceManager.GetString("coments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial Management &amp; Accounting.
        /// </summary>
        internal static string commercial_management_accounting {
            get {
                return ResourceManager.GetString("commercial_management_accounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commisions.
        /// </summary>
        internal static string commisions {
            get {
                return ResourceManager.GetString("commisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission.
        /// </summary>
        internal static string commission {
            get {
                return ResourceManager.GetString("commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission Calculation.
        /// </summary>
        internal static string commission_calculation {
            get {
                return ResourceManager.GetString("commission_calculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commissions.
        /// </summary>
        internal static string commissions {
            get {
                return ResourceManager.GetString("commissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string company {
            get {
                return ResourceManager.GetString("company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company&apos;s commission.
        /// </summary>
        internal static string companys_commission {
            get {
                return ResourceManager.GetString("companys_commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Method.
        /// </summary>
        internal static string connection_method {
            get {
                return ResourceManager.GetString("connection_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact and prospective clients.
        /// </summary>
        internal static string contact_and_prospective_clients {
            get {
                return ResourceManager.GetString("contact_and_prospective_clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Details.
        /// </summary>
        internal static string contact_details {
            get {
                return ResourceManager.GetString("contact_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        internal static string contact_information {
            get {
                return ResourceManager.GetString("contact_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        internal static string contract {
            get {
                return ResourceManager.GetString("contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Details.
        /// </summary>
        internal static string contract_details {
            get {
                return ResourceManager.GetString("contract_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contracts.
        /// </summary>
        internal static string contracts {
            get {
                return ResourceManager.GetString("contracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        internal static string countries {
            get {
                return ResourceManager.GetString("countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country of Taxation.
        /// </summary>
        internal static string country_of_taxation {
            get {
                return ResourceManager.GetString("country_of_taxation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string currency {
            get {
                return ResourceManager.GetString("currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string customer {
            get {
                return ResourceManager.GetString("customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Information.
        /// </summary>
        internal static string customer_information {
            get {
                return ResourceManager.GetString("customer_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        internal static string customer_name {
            get {
                return ResourceManager.GetString("customer_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers List.
        /// </summary>
        internal static string customers_list {
            get {
                return ResourceManager.GetString("customers_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data changes.
        /// </summary>
        internal static string data_changes {
            get {
                return ResourceManager.GetString("data_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Entry.
        /// </summary>
        internal static string data_entry {
            get {
                return ResourceManager.GetString("data_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data initialisation.
        /// </summary>
        internal static string data_initialisation {
            get {
                return ResourceManager.GetString("data_initialisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string date_ {
            get {
                return ResourceManager.GetString("date_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date from.
        /// </summary>
        internal static string date_from {
            get {
                return ResourceManager.GetString("date_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        internal static string date_of_birth {
            get {
                return ResourceManager.GetString("date_of_birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Issuing.
        /// </summary>
        internal static string date_of_issuing {
            get {
                return ResourceManager.GetString("date_of_issuing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Registration.
        /// </summary>
        internal static string date_of_registration {
            get {
                return ResourceManager.GetString("date_of_registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Start / End.
        /// </summary>
        internal static string date_start_end {
            get {
                return ResourceManager.GetString("date_start_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derivatives.
        /// </summary>
        internal static string derivatives {
            get {
                return ResourceManager.GetString("derivatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Settlement Advice.
        /// </summary>
        internal static string digital_settlement_advice {
            get {
                return ResourceManager.GetString("digital_settlement_advice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string discount {
            get {
                return ResourceManager.GetString("discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discretionary Portfolio Management.
        /// </summary>
        internal static string discretionary_portfolio_management {
            get {
                return ResourceManager.GetString("discretionary_portfolio_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DMS.
        /// </summary>
        internal static string dms {
            get {
                return ResourceManager.GetString("dms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc Type ID.
        /// </summary>
        internal static string doc_type_id {
            get {
                return ResourceManager.GetString("doc_type_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        internal static string document_type {
            get {
                return ResourceManager.GetString("document_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        internal static string documentation {
            get {
                return ResourceManager.GetString("documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        internal static string documents {
            get {
                return ResourceManager.GetString("documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents for applicants.
        /// </summary>
        internal static string documents_for_applicants {
            get {
                return ResourceManager.GetString("documents_for_applicants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOY.
        /// </summary>
        internal static string doy {
            get {
                return ResourceManager.GetString("doy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string duration {
            get {
                return ResourceManager.GetString("duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string e_mail {
            get {
                return ResourceManager.GetString("e_mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Portfolio.
        /// </summary>
        internal static string enter_profitCenter_subacc {
            get {
                return ResourceManager.GetString("enter_profitCenter_subacc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Basis.
        /// </summary>
        internal static string entry_basis {
            get {
                return ResourceManager.GetString("entry_basis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equities.
        /// </summary>
        internal static string equities {
            get {
                return ResourceManager.GetString("equities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETF.
        /// </summary>
        internal static string etf {
            get {
                return ResourceManager.GetString("etf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executed command.
        /// </summary>
        internal static string executed_command {
            get {
                return ResourceManager.GetString("executed_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution.
        /// </summary>
        internal static string Execution {
            get {
                return ResourceManager.GetString("Execution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution date.
        /// </summary>
        internal static string execution_date {
            get {
                return ResourceManager.GetString("execution_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution date from.
        /// </summary>
        internal static string execution_date_from {
            get {
                return ResourceManager.GetString("execution_date_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Venue.
        /// </summary>
        internal static string execution_venue {
            get {
                return ResourceManager.GetString("execution_venue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string exit_ {
            get {
                return ResourceManager.GetString("exit_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire Date.
        /// </summary>
        internal static string expire_date {
            get {
                return ResourceManager.GetString("expire_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facility Options.
        /// </summary>
        internal static string facility_options {
            get {
                return ResourceManager.GetString("facility_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father&apos;s Surname.
        /// </summary>
        internal static string fathers_surname {
            get {
                return ResourceManager.GetString("fathers_surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string fax {
            get {
                return ResourceManager.GetString("fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string female {
            get {
                return ResourceManager.GetString("female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        internal static string file_name {
            get {
                return ResourceManager.GetString("file_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string filter {
            get {
                return ResourceManager.GetString("filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final.
        /// </summary>
        internal static string final {
            get {
                return ResourceManager.GetString("final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Commission.
        /// </summary>
        internal static string final_commission {
            get {
                return ResourceManager.GetString("final_commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Advance.
        /// </summary>
        internal static string fixed_advance {
            get {
                return ResourceManager.GetString("fixed_advance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Income.
        /// </summary>
        internal static string fixed_income {
            get {
                return ResourceManager.GetString("fixed_income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        internal static string full_name {
            get {
                return ResourceManager.GetString("full_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Information.
        /// </summary>
        internal static string general_information {
            get {
                return ResourceManager.GetString("general_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTC.
        /// </summary>
        internal static string gtc {
            get {
                return ResourceManager.GetString("gtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HF Greek Products of Fixed Income.
        /// </summary>
        internal static string hf_greek_products_of_fixed_income {
            get {
                return ResourceManager.GetString("hf_greek_products_of_fixed_income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HF International Equities.
        /// </summary>
        internal static string hf_international_equities {
            get {
                return ResourceManager.GetString("hf_international_equities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HF International Fixed Income.
        /// </summary>
        internal static string hf_international_fixed_income {
            get {
                return ResourceManager.GetString("hf_international_fixed_income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string history {
            get {
                return ResourceManager.GetString("history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string inactive {
            get {
                return ResourceManager.GetString("inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income 80/20.
        /// </summary>
        internal static string income_80_20 {
            get {
                return ResourceManager.GetString("income_80_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexes.
        /// </summary>
        internal static string indexes {
            get {
                return ResourceManager.GetString("indexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informing.
        /// </summary>
        internal static string informing {
            get {
                return ResourceManager.GetString("informing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informing ways.
        /// </summary>
        internal static string informing_ways {
            get {
                return ResourceManager.GetString("informing_ways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institutional.
        /// </summary>
        internal static string institutional {
            get {
                return ResourceManager.GetString("institutional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment Advices.
        /// </summary>
        internal static string investment_advices {
            get {
                return ResourceManager.GetString("investment_advices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment Advise.
        /// </summary>
        internal static string investment_advise {
            get {
                return ResourceManager.GetString("investment_advise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment Committees.
        /// </summary>
        internal static string investment_committees {
            get {
                return ResourceManager.GetString("investment_committees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment Advices.
        /// </summary>
        internal static string investment_dvices {
            get {
                return ResourceManager.GetString("investment_dvices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment Policy.
        /// </summary>
        internal static string investment_policy {
            get {
                return ResourceManager.GetString("investment_policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment Proposals.
        /// </summary>
        internal static string investment_proposals {
            get {
                return ResourceManager.GetString("investment_proposals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investor Share.
        /// </summary>
        internal static string investor_share {
            get {
                return ResourceManager.GetString("investor_share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISIN.
        /// </summary>
        internal static string isin {
            get {
                return ResourceManager.GetString("isin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue.
        /// </summary>
        internal static string issue {
            get {
                return ResourceManager.GetString("issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuing Authority.
        /// </summary>
        internal static string issuing_authority {
            get {
                return ResourceManager.GetString("issuing_authority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joint.
        /// </summary>
        internal static string joint {
            get {
                return ResourceManager.GetString("joint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joint Owners.
        /// </summary>
        internal static string joint_owners {
            get {
                return ResourceManager.GetString("joint_owners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labels.
        /// </summary>
        internal static string labels {
            get {
                return ResourceManager.GetString("labels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Documentation.
        /// </summary>
        internal static string legal_documentation {
            get {
                return ResourceManager.GetString("legal_documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Documents.
        /// </summary>
        internal static string legal_documents {
            get {
                return ResourceManager.GetString("legal_documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Print.
        /// </summary>
        internal static string list_print {
            get {
                return ResourceManager.GetString("list_print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string male {
            get {
                return ResourceManager.GetString("male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        internal static string management {
            get {
                return ResourceManager.GetString("management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managment Fees.
        /// </summary>
        internal static string managment_fees {
            get {
                return ResourceManager.GetString("managment_fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managment Fees Reports.
        /// </summary>
        internal static string managment_fees_reports {
            get {
                return ResourceManager.GetString("managment_fees_reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital Status.
        /// </summary>
        internal static string marital_status {
            get {
                return ResourceManager.GetString("marital_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        internal static string maximize {
            get {
                return ResourceManager.GetString("maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        internal static string miscellaneous {
            get {
                return ResourceManager.GetString("miscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous Lists.
        /// </summary>
        internal static string miscellaneous_lists {
            get {
                return ResourceManager.GetString("miscellaneous_lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string mobile {
            get {
                return ResourceManager.GetString("mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money Market.
        /// </summary>
        internal static string money_market {
            get {
                return ResourceManager.GetString("money_market", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother&apos;s Surname.
        /// </summary>
        internal static string mothers_surname {
            get {
                return ResourceManager.GetString("mothers_surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mutual Fund.
        /// </summary>
        internal static string mutual_fund {
            get {
                return ResourceManager.GetString("mutual_fund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mutual Funds.
        /// </summary>
        internal static string mutual_funds {
            get {
                return ResourceManager.GetString("mutual_funds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        internal static string n {
            get {
                return ResourceManager.GetString("n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nee.
        /// </summary>
        internal static string nee {
            get {
                return ResourceManager.GetString("nee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs.
        /// </summary>
        internal static string needs {
            get {
                return ResourceManager.GetString("needs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Product.
        /// </summary>
        internal static string new_product {
            get {
                return ResourceManager.GetString("new_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Checked.
        /// </summary>
        internal static string not_checked {
            get {
                return ResourceManager.GetString("not_checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string note {
            get {
                return ResourceManager.GetString("note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string notes {
            get {
                return ResourceManager.GetString("notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Account.
        /// </summary>
        internal static string number_account {
            get {
                return ResourceManager.GetString("number_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only active clients.
        /// </summary>
        internal static string only_active_clients {
            get {
                return ResourceManager.GetString("only_active_clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Executed Transactions.
        /// </summary>
        internal static string only_executed_transactions {
            get {
                return ResourceManager.GetString("only_executed_transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only transmitted Transactions.
        /// </summary>
        internal static string only_transmitted_transactions {
            get {
                return ResourceManager.GetString("only_transmitted_transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only unexecuted Transactions.
        /// </summary>
        internal static string only_unexecuted_transactions {
            get {
                return ResourceManager.GetString("only_unexecuted_transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only untransmitted Transactions.
        /// </summary>
        internal static string only_untransmitted_transactions {
            get {
                return ResourceManager.GetString("only_untransmitted_transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string options {
            get {
                return ResourceManager.GetString("options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string order {
            get {
                return ResourceManager.GetString("order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Book.
        /// </summary>
        internal static string order_book {
            get {
                return ResourceManager.GetString("order_book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Cancelation.
        /// </summary>
        internal static string order_cancelation {
            get {
                return ResourceManager.GetString("order_cancelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Execution.
        /// </summary>
        internal static string order_execution {
            get {
                return ResourceManager.GetString("order_execution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Receipt Way.
        /// </summary>
        internal static string order_receipt_way {
            get {
                return ResourceManager.GetString("order_receipt_way", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders Search.
        /// </summary>
        internal static string orders_search {
            get {
                return ResourceManager.GetString("orders_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders Transfer.
        /// </summary>
        internal static string orders_transfer {
            get {
                return ResourceManager.GetString("orders_transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        internal static string p {
            get {
                return ResourceManager.GetString("p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package.
        /// </summary>
        internal static string package {
            get {
                return ResourceManager.GetString("package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package commission.
        /// </summary>
        internal static string package_commission {
            get {
                return ResourceManager.GetString("package_commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package discount.
        /// </summary>
        internal static string package_discount {
            get {
                return ResourceManager.GetString("package_discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package ID.
        /// </summary>
        internal static string package_id {
            get {
                return ResourceManager.GetString("package_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        internal static string parameter {
            get {
                return ResourceManager.GetString("parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF.
        /// </summary>
        internal static string pdf {
            get {
                return ResourceManager.GetString("pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pensive.
        /// </summary>
        internal static string pensive {
            get {
                return ResourceManager.GetString("pensive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Settings.
        /// </summary>
        internal static string personal_settings {
            get {
                return ResourceManager.GetString("personal_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personally.
        /// </summary>
        internal static string personally {
            get {
                return ResourceManager.GetString("personally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Born place.
        /// </summary>
        internal static string place_of_birth {
            get {
                return ResourceManager.GetString("place_of_birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Police ID Card.
        /// </summary>
        internal static string police_id_card {
            get {
                return ResourceManager.GetString("police_id_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Politically exposed persons.
        /// </summary>
        internal static string politically_exposed_persons {
            get {
                return ResourceManager.GetString("politically_exposed_persons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        internal static string portfolio {
            get {
                return ResourceManager.GetString("portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Mail.
        /// </summary>
        internal static string post_mail {
            get {
                return ResourceManager.GetString("post_mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        internal static string postcode {
            get {
                return ResourceManager.GetString("postcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Value.
        /// </summary>
        internal static string previous_value {
            get {
                return ResourceManager.GetString("previous_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        internal static string private_ {
            get {
                return ResourceManager.GetString("private_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string product {
            get {
                return ResourceManager.GetString("product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Categories.
        /// </summary>
        internal static string product_categories {
            get {
                return ResourceManager.GetString("product_categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product List.
        /// </summary>
        internal static string product_list {
            get {
                return ResourceManager.GetString("product_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Prices.
        /// </summary>
        internal static string product_prices {
            get {
                return ResourceManager.GetString("product_prices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string products {
            get {
                return ResourceManager.GetString("products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession.
        /// </summary>
        internal static string profession {
            get {
                return ResourceManager.GetString("profession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prospective.
        /// </summary>
        internal static string prospective {
            get {
                return ResourceManager.GetString("prospective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prospective Clients.
        /// </summary>
        internal static string prospective_clients {
            get {
                return ResourceManager.GetString("prospective_clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        internal static string provider {
            get {
                return ResourceManager.GetString("provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        internal static string publisher {
            get {
                return ResourceManager.GetString("publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionairre.
        /// </summary>
        internal static string questionnaire {
            get {
                return ResourceManager.GetString("questionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        internal static string rate {
            get {
                return ResourceManager.GetString("rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rates.
        /// </summary>
        internal static string rates {
            get {
                return ResourceManager.GetString("rates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt.
        /// </summary>
        internal static string receipt {
            get {
                return ResourceManager.GetString("receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt time.
        /// </summary>
        internal static string receipt_time {
            get {
                return ResourceManager.GetString("receipt_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt way.
        /// </summary>
        internal static string receipt_way {
            get {
                return ResourceManager.GetString("receipt_way", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt way type.
        /// </summary>
        internal static string receipt_way_type {
            get {
                return ResourceManager.GetString("receipt_way_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive and Transmit.
        /// </summary>
        internal static string receive_and_transmit {
            get {
                return ResourceManager.GetString("receive_and_transmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving Transmission.
        /// </summary>
        internal static string receiving_transmission {
            get {
                return ResourceManager.GetString("receiving_transmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient Name.
        /// </summary>
        internal static string recipient_name {
            get {
                return ResourceManager.GetString("recipient_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Currency.
        /// </summary>
        internal static string reference_currency {
            get {
                return ResourceManager.GetString("reference_currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        internal static string release_date {
            get {
                return ResourceManager.GetString("release_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Characters.
        /// </summary>
        internal static string remaining_characters {
            get {
                return ResourceManager.GetString("remaining_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrocession Fees.
        /// </summary>
        internal static string retrocession_fees {
            get {
                return ResourceManager.GetString("retrocession_fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reuters Code.
        /// </summary>
        internal static string reuters_code {
            get {
                return ResourceManager.GetString("reuters_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM.
        /// </summary>
        internal static string rm {
            get {
                return ResourceManager.GetString("rm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving completed successfully.
        /// </summary>
        internal static string saving_completed_successfully {
            get {
                return ResourceManager.GetString("saving_completed_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Investment Proposals.
        /// </summary>
        internal static string search_investment_proposals {
            get {
                return ResourceManager.GetString("search_investment_proposals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sectors.
        /// </summary>
        internal static string sectors {
            get {
                return ResourceManager.GetString("sectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Securities Account.
        /// </summary>
        internal static string securities_account {
            get {
                return ResourceManager.GetString("securities_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        internal static string sell {
            get {
                return ResourceManager.GetString("sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send SMS.
        /// </summary>
        internal static string send_sms {
            get {
                return ResourceManager.GetString("send_sms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        internal static string service {
            get {
                return ResourceManager.GetString("service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service package.
        /// </summary>
        internal static string service_package {
            get {
                return ResourceManager.GetString("service_package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Providers.
        /// </summary>
        internal static string service_providers {
            get {
                return ResourceManager.GetString("service_providers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string services {
            get {
                return ResourceManager.GetString("services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settlement Advice Checking.
        /// </summary>
        internal static string settlement_advice_checking {
            get {
                return ResourceManager.GetString("settlement_advice_checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        internal static string sex {
            get {
                return ResourceManager.GetString("sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Documents.
        /// </summary>
        internal static string shared_documents {
            get {
                return ResourceManager.GetString("shared_documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show canceled orders.
        /// </summary>
        internal static string show_canceled_orders {
            get {
                return ResourceManager.GetString("show_canceled_orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SN.
        /// </summary>
        internal static string sn {
            get {
                return ResourceManager.GetString("sn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        internal static string sound {
            get {
                return ResourceManager.GetString("sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spouse&apos;s Surname.
        /// </summary>
        internal static string spouses_surname {
            get {
                return ResourceManager.GetString("spouses_surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stages of Contracts.
        /// </summary>
        internal static string stages_of_ontracts {
            get {
                return ResourceManager.GetString("stages_of_ontracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Date.
        /// </summary>
        internal static string starting_date {
            get {
                return ResourceManager.GetString("starting_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock exchange.
        /// </summary>
        internal static string stock_exchange {
            get {
                return ResourceManager.GetString("stock_exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        internal static string subaccount {
            get {
                return ResourceManager.GetString("subaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string subject {
            get {
                return ResourceManager.GetString("subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string surname {
            get {
                return ResourceManager.GetString("surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Office.
        /// </summary>
        internal static string tax_office {
            get {
                return ResourceManager.GetString("tax_office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        internal static string telephone {
            get {
                return ResourceManager.GetString("telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary Import Data.
        /// </summary>
        internal static string temporary_import_data {
            get {
                return ResourceManager.GetString("temporary_import_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string text {
            get {
                return ResourceManager.GetString("text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The introduction of the  surname is mandatory.
        /// </summary>
        internal static string the_introduction_of_the_surname_is_mandatory {
            get {
                return ResourceManager.GetString("the_introduction_of_the_surname_is_mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIN.
        /// </summary>
        internal static string tin {
            get {
                return ResourceManager.GetString("tin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string tools {
            get {
                return ResourceManager.GetString("tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools Options.
        /// </summary>
        internal static string tools_options {
            get {
                return ResourceManager.GetString("tools_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools Send SMS.
        /// </summary>
        internal static string tools_send_sms {
            get {
                return ResourceManager.GetString("tools_send_sms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools Send SMS.
        /// </summary>
        internal static string tools_snd_sms {
            get {
                return ResourceManager.GetString("tools_snd_sms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        internal static string transaction {
            get {
                return ResourceManager.GetString("transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction commission.
        /// </summary>
        internal static string transaction_commission {
            get {
                return ResourceManager.GetString("transaction_commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        internal static string transactions {
            get {
                return ResourceManager.GetString("transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions List.
        /// </summary>
        internal static string transactions_list {
            get {
                return ResourceManager.GetString("transactions_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions Search.
        /// </summary>
        internal static string transactions_search {
            get {
                return ResourceManager.GetString("transactions_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmission.
        /// </summary>
        internal static string transmission {
            get {
                return ResourceManager.GetString("transmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmission time.
        /// </summary>
        internal static string transmission_time {
            get {
                return ResourceManager.GetString("transmission_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmitter.
        /// </summary>
        internal static string transmitter {
            get {
                return ResourceManager.GetString("transmitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turnover.
        /// </summary>
        internal static string turnover {
            get {
                return ResourceManager.GetString("turnover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turnover &amp; Fees.
        /// </summary>
        internal static string turnover_fees {
            get {
                return ResourceManager.GetString("turnover_fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of issue.
        /// </summary>
        internal static string type_of_issue {
            get {
                return ResourceManager.GetString("type_of_issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until.
        /// </summary>
        internal static string until_ {
            get {
                return ResourceManager.GetString("until_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates file.
        /// </summary>
        internal static string updates_file {
            get {
                return ResourceManager.GetString("updates_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Via EAM-NET.
        /// </summary>
        internal static string via_eam_net {
            get {
                return ResourceManager.GetString("via_eam_net", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anamoni.
        /// </summary>
        internal static string waiting {
            get {
                return ResourceManager.GetString("waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong amount.
        /// </summary>
        internal static string wrong_amount {
            get {
                return ResourceManager.GetString("wrong_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP.
        /// </summary>
        internal static string zip {
            get {
                return ResourceManager.GetString("zip", resourceCulture);
            }
        }
    }
}
